logging

diff --git a/.github/workflows/docker-compose.yml b/.github/workflows/docker-compose.yml
--- a/.github/workflows/docker-compose.yml
+++ b/.github/workflows/docker-compose.yml
@@ -15,9 +15,13 @@ jobs:
           chmod 0600 celestia-node/full0/nodekey0
           chmod 0600 celestia-node/full1/nodekey1
           docker-compose -f docker/docker-compose-full-node.yml up -d
-          sleep 10
+          sleep 30
           node0=$(docker run --network docker_localnet --rm curlimages/curl:7.80.0 -s "192.167.10.5:26657/block?height=1" | jq .result.block_id.hash)
+          echo $node0
           node1=$(docker run --network docker_localnet --rm curlimages/curl:7.80.0 -s "192.167.10.5:26657/block?height=1" | jq .result.block_id.hash)
+          echo $node1
           node2=$(docker run --network docker_localnet --rm curlimages/curl:7.80.0 -s "192.167.10.5:26657/block?height=1" | jq .result.block_id.hash)
+          echo $node2
           node3=$(docker run --network docker_localnet --rm curlimages/curl:7.80.0 -s "192.167.10.5:26657/block?height=1" | jq .result.block_id.hash)
-          if [ $node0 -ne "null" ] && [ $node0 = $node1 ] && [ $node0 = $node2 ] && [ $node0 = $node3 ]; then echo "$node0: success" && exit 0; else echo "failure" && exit 1; fi
+          echo $node3
+          if [ $node0 != null ] && [ $node0 = $node1 ] && [ $node0 = $node2 ] && [ $node0 = $node3 ]; then echo "$node0: success" && exit 0; else echo "failure" && exit 1; fi
