typo

diff --git a/.github/workflows/docker-compose.yml b/.github/workflows/docker-compose.yml
--- a/.github/workflows/docker-compose.yml
+++ b/.github/workflows/docker-compose.yml
@@ -20,4 +20,4 @@ jobs:
           node1=$(docker run --network docker_localnet --rm curlimages/curl:7.80.0 -s "192.167.10.5:26657/block?height=1" | jq .result.block_id.hash)
           node2=$(docker run --network docker_localnet --rm curlimages/curl:7.80.0 -s "192.167.10.5:26657/block?height=1" | jq .result.block_id.hash)
           node3=$(docker run --network docker_localnet --rm curlimages/curl:7.80.0 -s "192.167.10.5:26657/block?height=1" | jq .result.block_id.hash)
-          if [ $node -ne "null" ] && [ $node0 = $node1 ] && [ $node0 = $node2 ] && [ $node0 = $node3 ]; then echo "$node0: success" && exit 0; else echo "failure" && exit 1; fi
+          if [ $node0 -ne "null" ] && [ $node0 = $node1 ] && [ $node0 = $node2 ] && [ $node0 = $node3 ]; then echo "$node0: success" && exit 0; else echo "failure" && exit 1; fi
